### PR TITLE
fix NumberFormatException for too high int value generated from Xeger

### PR DESCRIPTION
**Pull request by me3x**

### CODE REVIEW

**Comment by OlgaMaciaszek** [comment]
Hello @me3x Is there any issue that can be linked with this PR?

**Comment by me3x** [comment]
@OlgaMaciaszek I don't know about any.

**Comment by OlgaMaciaszek** [comment]
@me3x Please create a corresponding issue and link to this PR. Also, please fix the failing tests.

**Comment by marcingrzejszczak** [comment]
@me3x any progress with this one?

**Pull request closed without merging**
