### PR TITLE
WIP: Add Kotlin DSL support #434

### PR DESCRIPTION
**Pull request by soudmaijer**
I still have a few loose ends, but opening the pull request anyway so you can give some feedback/review comments.

Open issues:
- There are some failing tests in the samples/standalone/kotlin modules, need to check this.
- varags in request/response.body() does not seem to work well with the standalone samples.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@soudmaijer Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-contract&pullRequestId=561)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-cloud/spring-cloud-contract&pullRequestId=561) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by marcingrzejszczak** [comment]
@soudmaijer you have to sign the CLA :) @sdeleuze can you check this out ? :)

**Comment by pivotal-issuemaster** [comment]
@soudmaijer Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-contract&pullRequestId=561)!

**Comment by marcingrzejszczak** [comment]
@sdeleuze wdyt? :)

**Comment by sdeleuze** [comment]
Seems mostly ok, my main remaining open question is about individual attributes like `status`, `method` or `url`, should we use named parameters instead of dedicated functions for them?

**Comment by marcingrzejszczak** [comment]
@soudmaijer WDYT ^^ ?

**Comment by soudmaijer** [comment]
@marcingrzejszczak I will continue to work on it coming friday. I encountered some other annoying issues as well, extension functions in Kotlin have some limitations as well. In the end I think it will be better to add some more kotlin classes instead of delegating everything to the groovy code. It is not always doing exactly what I want.

**Comment by marcingrzejszczak** [comment]
I've merged https://github.com/spring-cloud/spring-cloud-contract/issues/575 so most likely it influences this PR

**Comment by marcingrzejszczak** [comment]
@soudmaijer what kind of help do you need for us to merge it by Wednesday? :D

**Comment by soudmaijer** [comment]
@marcingrzejszczak what I wanted to fix is to remove the need for the explicit .clientValue invocation:

- https://github.com/soudmaijer/spring-cloud-contract/blob/master/samples/standalone/kotlin/kotlin-http-server/src/test/resources/contracts/fraudname/shouldReturnNonFraudForTheName.kts#L19
- https://github.com/soudmaijer/spring-cloud-contract/blob/master/samples/standalone/kotlin/kotlin-http-server/src/test/resources/contracts/fraudname/shouldReturnNonFraudForTheName.kts#L22

And when I use a single Pair entry, I still need to wrap with a mapOf():

- https://github.com/soudmaijer/spring-cloud-contract/blob/master/samples/standalone/kotlin/kotlin-http-server/src/test/resources/contracts/fraudname/shouldReturnNonFraudForTheName.kts#L18

The current samples work, but there is room for improvement!

**Comment by marcingrzejszczak** [comment]
I see. Maybe I should do a fast crash course of Kotlin to help you with it ;) maybe @sdeleuze has some suggestions on this topic?

**Comment by sdeleuze** [comment]
I have cloned @soudmaijer repo to have a look since I also think there is room for imrprovement before merging/releasing, but I have a lot of unresolved references, is there any special IDE setup required to get code completion working?

**Comment by marcingrzejszczak** [comment]
https://github.com/spring-cloud/spring-cloud-contract/#how-to-build-it :)

```
You need to have all the necessary Groovy plugins installed for your IDE to properly resolve the sources. For example in Intellij IDEA having both Eclipse Groovy Compiler Plugin & GMavenPlus Intellij Plugin results in properly imported project.
```

**Comment by sdeleuze** [comment]
Thanks for the hint, it seems to work for `spring-cloud-contract-spec-kotlin` but not for `samples`.

**Comment by marcingrzejszczak** [comment]
Ah you mean the standalone samples? They are not part of the project. You have to import them separately by their parent - for example for messaging import in your IDE this project https://github.com/spring-cloud/spring-cloud-contract/blob/master/samples/standalone/messaging/pom.xml

**Comment by soudmaijer** [comment]
@marcingrzejszczak @sdeleuze What I was working on locally is implementing a Kotlin version of the Request, Response and Body classes. This way I have way more flexibility instead of writing extension functions for the Groovy classes. 

@marcingrzejszczak What would be nice IMO if there would some kind of Java interface for these DSL classes which I can then implement in the Kotlin version. I was trying to extract one based on the Groovy classes, but I am not 100% sure what methods are mandatory and which one are actually deprecated. What do you think?

**Comment by soudmaijer** [comment]
@sdeleuze you need to include the standalone samples pom as a separate project in IntelliJ.

**Comment by marcingrzejszczak** [comment]
> @marcingrzejszczak What would be nice IMO if there would some kind of Java interface for these DSL classes which I can then implement in the Kotlin version. I was trying to extract one based on the Groovy classes, but I am not 100% sure what methods are mandatory and which one are actually deprecated. What do you think?

Sure, why not. However, with all the delegations that we're doing there, it can be a very tedious task. I don't know if it actually really makes sense to do it.

**Comment by marcingrzejszczak** [comment]
@soudmaijer do you think that we could actually merge this before 4.04 ? :P

**Comment by marcingrzejszczak** [comment]
@soudmaijer happy Easter holidays ;) do you need some help with this PR ?

**Comment by soudmaijer** [comment]
@marcingrzejszczak I was/am working on a Kotlin based model for the DSL: https://github.com/soudmaijer/spring-cloud-contract/commits/WIP . Last week I was not able to work on it, will continue this week. Using Kotlin classes instead of Groovy works way better because I have more control over what is happening. I want to have a working version ready this week.

**Comment by marcingrzejszczak** [comment]
Cool! I don't think you've introduced any breaking changes right? Also please note that with the pact feature we needed to slightly modify the DSL. Instead of stub matchers and test matchers there are body matchers inside request and response. The old approach is not removed, it's deprecated.

**Comment by marcingrzejszczak** [comment]
Hey @soudmaijer ! I can help you with this PR but can you elaborate on what exactly was your plan of action? :P That way I can take it over and try to merge it to master before RC1.

**Comment by sdeleuze** [comment]
@soudmaije Any chance you could update the PR with the full Kotlin API we discussed in order to be able to ship the Kotlin DSL in Spring Cloud Contract 2.0.0? If not I think it is better to not merge current one that exposes Groovy API.

**Comment by soudmaijer** [comment]
@marcingrzejszczak let me contact you tomorrow via gitter to discuss this.

@sdeleuze I agree on the full Kotlin API. I started working on it. I will update my fork tomorrow.

**Comment by marcingrzejszczak** [comment]
@soudmaijer how is it going? ;)

**Comment by soudmaijer** [comment]
Planning on picking this up in the next week.

Op vr 13 jul. 2018 23:02 schreef Marcin Grzejszczak <
notifications@github.com>:

**Comment by marcingrzejszczak** [comment]
@soudmaijer any chances we can do it for RC1 ?

**Comment by marcingrzejszczak** [comment]
hey @soudmaijer ! How is it going? ;) Just FYI, the latest master branch code contains changes where the `Contract` class is fully written in Java. I remember that you said that it's, to some extent, a blocker for the Kotlin DSL. Now that issue should be gone. Are you willing to continue with this PR then? :)

**Comment by marcingrzejszczak** [comment]
Closing this due to inactivity. @TYsewyn is working on a new version.

**Pull request closed without merging**
