### PR TITLE
Gradle plugin - improve compatibility with Configuration Cache

### LINKED ISSUE #1824: Spring Cloud Contract Gradle Plugin is not compatible with Gradle Configuration Cache
**Describe the bug**

When I use the Spring Cloud Contract Gradle Plugin and I have [Gradle Configuration cache](https://docs.gradle.org/current/userguide/configuration_cache.html) enabled, I get a lot of warnings about Spring Cloud Contract Gradle Plugin using 'Project' at execution time.

```
20 problems were found storing the configuration cache, 8 of which seem unique.
- Task `:application:copyContracts` of type `org.springframework.cloud.contract.verifier.plugin.ContractsCopyTask`: invocation of 'Task.project' at execution time is unsupported.
  See https://docs.gradle.org/7.5.1/userguide/configuration_cache.html#config_cache:requirements:use_project_during_execution
- Task `:application:generateClientStubs` of type `org.springframework.cloud.contract.verifier.plugin.GenerateClientStubsFromDslTask`: invocation of 'Task.project' at execution time is unsupported.
  See https://docs.gradle.org/7.5.1/userguide/configuration_cache.html#config_cache:requirements:use_project_during_execution
- Task `:subprojectAlpha:copyContracts` of type `org.springframework.cloud.contract.verifier.plugin.ContractsCopyTask`: invocation of 'Task.project' at execution time is unsupported.
  See https://docs.gradle.org/7.5.1/userguide/configuration_cache.html#config_cache:requirements:use_project_during_execution
- Task `:subprojectAlpha:rest:generateClientStubs` of type `org.springframework.cloud.contract.verifier.plugin.GenerateClientStubsFromDslTask`: invocation of 'Task.project' at execution time is unsupported.
- ...
```

The Configuration Cache docs provide some good steps on how to fix these problems https://docs.gradle.org/current/userguide/configuration_cache.html#config_cache:requirements:use_project_during_execution

### Fixing

From quickly looking at Spring Cloud Contract Gradle Plugin, I think most of these problems are relatively easy to solve.

* create an `@Input Property<String>` for storing the project name and group, instead of fetching them on-the-fly from `getProject()` https://github.com/spring-cloud/spring-cloud-contract/blob/f9c330523979909f41807b33fdd683ac58d6fd42/spring-cloud-contract-tools/spring-cloud-contract-gradle-plugin/src/main/java/org/springframework/cloud/contract/verifier/plugin/ContractsCopyTask.java#L161-L168
* [Inject the appropriate Gradle Build Services](https://docs.gradle.org/current/userguide/custom_gradle_types.html#service_injection), instead of accessing them from `getProject()`
  * https://github.com/spring-cloud/spring-cloud-contract/blob/f9c330523979909f41807b33fdd683ac58d6fd42/spring-cloud-contract-tools/spring-cloud-contract-gradle-plugin/src/main/java/org/springframework/cloud/contract/verifier/plugin/ContractsCopyTask.java#L209
  * https://github.com/spring-cloud/spring-cloud-contract/blob/f9c330523979909f41807b33fdd683ac58d6fd42/spring-cloud-contract-tools/spring-cloud-contract-gradle-plugin/src/main/java/org/springframework/cloud/contract/verifier/plugin/ContractsCopyTask.java#L190

### Testing

Compatibility with the Configuration Cache can be tested https://docs.gradle.org/current/userguide/configuration_cache.html#config_cache:testing, however I don't think the existing tests use Gradle TestKit, so implementing this could be some work?

### PR DESCRIPTION
**Pull request by aSemy**
Avoid using Project during task execution

* Use properties to capture the Project group/name/version
* Inject and use build services, rather than using Project
* minor refactor (tidy `buildRootPath()`, fix some Javadoc)

The tests pass, but I haven't verified that the plugin is now compatible with the Gradle Configuration Cache, so I'm marking this as 'draft'.

(hopefully) fixes #1824

### CODE REVIEW

**Comment by marcingrzejszczak** [comment]
hey @shanman190 , WDYT?

**Comment by marcingrzejszczak** [comment]
@aSemy can you please resolve the conflicts?

**Comment by shanman190** [comment]
@marcingrzejszczak, the implementation looks good to me and is compatible with the Gradle 6.8 baseline for 3.1. Only thing that stuck out to me was the code style not following the Spring defaults, but that's minor.

**Comment by marcingrzejszczak** [comment]
@aSemy can we merge this?

**Comment by aSemy** [comment]
@marcingrzejszczak definitely!

**Comment by marcingrzejszczak** [comment]
Congrats @aSemy on your first contribution :)

**Pull request merged**
