### PR TITLE
Fix OptionalProperty producing wrong output with ClientDslProperty & ServerDslProperty

### PR DESCRIPTION
**Pull request by artemy**
Fix improperly accessed optional values; ServerDslProperty incorrectly wrapped by OptionalProperty

Fixes gh-1808

### CODE REVIEW

**Comment by marcingrzejszczak** [comment]
Hey, thanks for this great PR. Can we do it against `3.1.x` branch? I will merge it forward to `main` then.

**Comment by artemy** [comment]
I reckon you should be able to do it to `3.1.x` too, that's where I actually was developing and testing it

**Comment by marcingrzejszczak** [comment]
OK so if this passes I'll cherry pick the commit to 3.1.x. No problem!

**Comment by artemy** [comment]
There are some issues with the main branch pipeline

**Comment by marcingrzejszczak** [comment]
Thanks for the PR ! Error is not related to your changes

**Pull request merged**
