### PR TITLE
#883: Further DirtiesContext fix where the context is refreshed during the test phase.

### PR DESCRIPTION
**Pull request by boothen**
The original commit fixed the DirtiesContext issue for JUnit/SpringRunner tests. However, the issue was not fixed where the context was refreshed during the test phase. This occurs when using test frameworks like cucumber.

This latest PR avoids updating the httpsPortDynamic where a fixed port has been specified.

### CODE REVIEW

**Comment by OlgaMaciaszek** [comment]
Hello @boothen Thanks for the PR. The tests are failing. Could you have a look at it?

**Comment by boothen** [comment]
The test failures look unrelated to any change I've made. I've also cloned the master branch and it has the same test failures. It looks related to the snapshot build of spring-boot-autoconfigure.

> Description:
> 
> An attempt was made to call a method that does not exist. The attempt was made from the following location:
> 
>     org.springframework.boot.autoconfigure.web.servlet.WebMvcAutoConfiguration$EnableWebMvcConfiguration.configureHandlerExceptionResolvers(WebMvcAutoConfiguration.java:565)
> 
> The following method did not exist:
> 
>     org.springframework.boot.autoconfigure.web.servlet.WebMvcAutoConfiguration$EnableWebMvcConfiguration.addDefaultHandlerExceptionResolvers(Ljava/util/List;)V
> 
> The method's class, org.springframework.boot.autoconfigure.web.servlet.WebMvcAutoConfiguration$EnableWebMvcConfiguration, is available from the following locations:
> 
>     jar:file:/Users/boothen/.m2/repository/org/springframework/boot/spring-boot-autoconfigure/2.2.0.BUILD-SNAPSHOT/spring-boot-autoconfigure-2.2.0.BUILD-SNAPSHOT.jar!/org/springframework/boot/autoconfigure/web/servlet/WebMvcAutoConfiguration$EnableWebMvcConfiguration.class
> 
> It was loaded from the following location:
> 
>     file:/Users/boothen/.m2/repository/org/springframework/boot/spring-boot-autoconfigure/2.2.0.BUILD-SNAPSHOT/spring-boot-autoconfigure-2.2.0.BUILD-SNAPSHOT.jar
> 
> 
> Action:
> 
> Correct the classpath of your application so that it contains a single, compatible version of org.springframework.boot.autoconfigure.web.servlet.WebMvcAutoConfiguration$EnableWebMvcConfiguration

**Comment by OlgaMaciaszek** [comment]
@boothen I see these tests also currently fail on master. Will fix that and rerun your PR tests when it's done.

**Comment by OlgaMaciaszek** [comment]
Hello @boothen could you please submit this PR against branch 2.1.x instead? Your previous changes were merged to 2.1.

**Comment by boothen** [comment]
Hi @OlgaMaciaszek, I've created a new PR to merge against 2.1.x - #1040. I've made a mess of this one so will close it.

**Pull request closed without merging**
