### PR TITLE
add <excludeBuildFolders> to exclude target/build directory from JAR file.

### PR DESCRIPTION
**Pull request by jyukutyo**
A JAR file includes same two json files, such as client1/expectation.json. See below.

```
$ mvn clean install -DskipTests

$ unzip -l target/server-0.0.1-SNAPSHOT-stubs.jar
Archive:  target/server-0.0.1-SNAPSHOT-stubs.jar
  Length     Date   Time    Name
 --------    ----   ----    ----
      171  01-20-17 13:14   META-INF/MANIFEST.MF
        0  01-20-17 13:14   META-INF/
        0  01-20-17 13:14   contracts/
        0  01-20-17 13:14   contracts/client1/
        0  01-20-17 13:14   contracts/client2/
        0  01-20-17 13:14   contracts/client3/
        0  01-20-17 13:14   mappings/
        0  01-20-17 13:14   mappings/client1/
        0  01-20-17 13:14   mappings/client2/
        0  01-20-17 13:14   mappings/client3/
        0  01-20-17 13:14   mappings/target/
        0  01-20-17 13:14   mappings/target/stubs/
        0  01-20-17 13:14   mappings/target/stubs/contracts/
        0  01-20-17 13:14   mappings/target/stubs/contracts/client1/
        0  01-20-17 13:14   mappings/target/stubs/contracts/client2/
        0  01-20-17 13:14   mappings/target/stubs/contracts/client3/
     2614  01-20-17 13:14   contracts/client1/expectation.groovy
      602  01-20-17 13:14   mappings/client2/expectation.json
      602  01-20-17 13:14   mappings/target/stubs/contracts/client2/expectation.json
     2499  01-20-17 13:14   contracts/client2/expectation.groovy
      609  01-20-17 13:14   mappings/target/stubs/contracts/client1/expectation.json
     2499  01-20-17 13:14   contracts/client3/expectation.groovy
      602  01-20-17 13:14   mappings/client3/expectation.json
      602  01-20-17 13:14   mappings/target/stubs/contracts/client3/expectation.json
      609  01-20-17 13:14   mappings/client1/expectation.json
 --------                   -------
    11409                   25 files
```

I added `<excludeBuildFolders>true</excludeBuildFolders>` to pom.xml to exclude target directory from a JAR file. After doing this, it includes only one json file per expectation.groovy file.

```
$ unzip -l target/server-0.0.1-SNAPSHOT-stubs.jar
Archive:  target/server-0.0.1-SNAPSHOT-stubs.jar
  Length     Date   Time    Name
 --------    ----   ----    ----
      171  01-20-17 13:06   META-INF/MANIFEST.MF
        0  01-20-17 13:06   META-INF/
        0  01-20-17 13:06   contracts/
        0  01-20-17 13:06   contracts/client1/
        0  01-20-17 13:06   contracts/client2/
        0  01-20-17 13:06   contracts/client3/
        0  01-20-17 13:06   mappings/
        0  01-20-17 13:06   mappings/client1/
        0  01-20-17 13:06   mappings/client2/
        0  01-20-17 13:06   mappings/client3/
     2614  01-20-17 13:06   contracts/client1/expectation.groovy
      602  01-20-17 13:06   mappings/client2/expectation.json
     2499  01-20-17 13:06   contracts/client2/expectation.groovy
     2499  01-20-17 13:06   contracts/client3/expectation.groovy
      609  01-20-17 13:06   mappings/client1/expectation.json
      602  01-20-17 13:06   mappings/client3/expectation.json
 --------                   -------
     9596                   16 files
```

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@jyukutyo Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-contract&pullRequestId=198)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-cloud/spring-cloud-contract&pullRequestId=198) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/faq) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@jyukutyo Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-contract&pullRequestId=198)!

**Comment by marcingrzejszczak** [comment]
It's already done https://github.com/spring-cloud-samples/spring-cloud-contract-samples/blob/master/beer_contracts/src/main/resources/contracts/com/example/beer-api-producer-external/pom.xml#L26 and https://github.com/spring-cloud/spring-cloud-contract/blob/master/spring-cloud-contract-tools/spring-cloud-contract-gradle-plugin/src/main/groovy/org/springframework/cloud/contract/verifier/plugin/ContractVerifierExtension.groovy#L142

**Comment by marcingrzejszczak** [comment]
Done via https://github.com/spring-cloud/spring-cloud-contract/commit/152d598bff19a8d79dce888535850ec7d068903f

**Comment by marcingrzejszczak** [comment]
Thanks for the PR!

**Pull request closed without merging**
