### PR TITLE
Updated description of byType testMatcher

### PR DESCRIPTION
**Pull request by WhyINeedToFillUsername**
I only changed line 483. GitHub is highlighting line 1202. which I didn't do anything with, I hope it is not a CRLF change or sth.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@WhyINeedToFillUsername Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-contract&pullRequestId=394)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-cloud/spring-cloud-contract&pullRequestId=394) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by marcingrzejszczak** [comment]
@WhyINeedToFillUsername you need to sign the CLA - https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-contract&pullRequestId=394

**Comment by WhyINeedToFillUsername** [comment]
Omg. Signed.

**Comment by marcingrzejszczak** [comment]
Hmm and can you click on the `Details` button next to the failed check?

**Comment by WhyINeedToFillUsername** [comment]
Yes, it says "Thank you for signing the Agreement! The contributor license agreement checks on spring-cloud/spring-cloud-contract/pull/394 should now pass."

**Comment by marcingrzejszczak** [comment]
Congrats on your first contribution!! :) 🍰 ✨ 🎉

**Comment by WhyINeedToFillUsername** [comment]
Thanks :)

**Pull request merged**
