### PR TITLE
Adds metadata to contracts

### LINKED ISSUE #1078: Support for postServeAction
Hi,

I'm trying to use this [wiremock extension](https://github.com/wiremock/wiremock-webhooks-extension) which uses `postServeAction` in wiremock DSL. 

Is there any way to use `postServeAction` with the currect version with SCC or maybe support it in the future?

Thanks,
Abbas

### LINKED ISSUE #1340: Contract stub with non fixed delay
Hi,

we wonder if you plan to add more customisation for the delay in the spring cloud contract.
For the moment there is only fixedDelayMilliseconds. I saw that wiremock used fixedDelay, delayDistribution and chunkedDribbleDelay.

It will be a real nice to have, because sometimes we want to use the stub generated to simulate the real call to the service (with realistic delay).

Thanks,
Best regards, 
Julian

### PR DESCRIPTION
**Pull request by marcingrzejszczak**
fixes #1340 
* you can add the following entry in the `wiremock` metadata map
```groovy
Contract.make {
		request {
			method GET()
			url '/drunks'
		}
		response {
			status OK()
			body([
				count: 100
			])
			headers {
				contentType("application/json")
			}
		}
		metadata([wiremock: '''\
	{
		"response" : {
			"delayDistribution": {
                    "type": "lognormal",
                    "median": 80,
                    "sigma": 0.4
            }
		}
	}
'''
		])
```

fixes #1078 , #1406 
* you can add the following entry in the `wiremock` metadata map (unfortunately webhooks won't work due to a mismatch of versions between WireMock 2.21 (used by extension) and 2.27 (used by Spring Cloud Contract).
```groovy
Contract.make {
		request {
			method GET()
			url '/drunks'
		}
		response {
			status OK()
			body([
				count: 100
			])
			headers {
				contentType("application/json")
			}
		}
		metadata([wiremock: '''\
	{
		"postServeActions" : {
    "webhook" : {
      "headers" : {
        "Content-Type" : "application/json"
      },
      "method" : "POST",
      "body" : "{ \"result\": \"SUCCESS\" }",
      "url" : "http://localhost:56299/callback"
    }
  }
	}
'''
		])
```

as for #1084 we could add a metadata entry that would be of `restdocs` key and there we could apply additional work related to restdocs (wdyt @wkorando @artemptushkin )

cc @Buzzardo - there is documentation changed here so once this gets merged could you please do a editing pass?

### CODE REVIEW

**Comment by artemptushkin** [comment]
@marcingrzejszczak hi, sorry what does mean `restdocs` key? Do you have code sample/example of usage? Metadata looks okay, depends on `restdocs` view of it

**Comment by marcingrzejszczak** [comment]
So in the `metadata(...)` section you could set e.g. `metadata("restdocs",...)` or `metadata("description",...)` in a way similar to this one

```yaml
name: add-produce
description: Operation for adding a new produce item
request:
  method: POST
  url: /api/v1/produce
  headers:
    Content-Type: application/json;charset=UTF-8
  body:
    name: "Kiwi"
    subName: ""
    quantity: 75
  matchers:
    headers:
    - key: Content-Type
      regex: "application/json.*"
    body:
      - path: $.quantity
        type: by_regex
        value: "[0-9]+"
      - path: $.name
        type: by_regex
        predefined: only_alpha_unicode
  metadata:
  restdocs:
    headers:
    - key: Content-Type
      description: "Produce endpoint expects JSON encoded request bodies"
    body:
      - path: $.name
        description: "Name of new produce item"
      - path: $.subName
        description: "Sub-name of new produce item providing a more specific name for the produce item"
      - path: $.quantity
        description: "Number of produce item currently in stock"
response:
  status: 200
  body:
    id: 10
    name: "Kiwi"
    subName: ""
    quantity: 75
  headers:
    Content-Type: application/json;charset=UTF-8
  matchers:
    body:
      - path: $.id
        type: by_regex
        value: "[0-9]+"
  metadata:
   restdocs:
    headers:
    - key: Content-Type
      description: "Produce endpoint provides responses in JSON"
    body:
      - path: $.id
        description: "Unique id of new produce item"
      - path: $.name
        description: "Name of new produce item"
      - path: $.subName
        description: "Sub-name of new produce item providing a more specific name for the produce item"
      - path: $.quantity
        description: "Number of produce item currently in stock"
```

That way we'd put it into the `metadata` map with a `restdocs` key.

**Comment by artemptushkin** [comment]
It is possible, it is better to add clean documentation for it with a good example, cause we have strange String / yaml / json conversions here.
As I see usage sample on contract side:
```groovy
metadata("""
    restdocs:
         headers:
             - key: Content-Type
               description: "Produce endpoint provides responses in JSON"
""")
```
Thanks :)

**Comment by marcingrzejszczak** [comment]
There's no example atm that's why we're prototyping. I've reformatted the example

```yaml
name: add-produce
description: Operation for adding a new produce item
request:
  method: POST
  url: /api/v1/produce
  headers:
    Content-Type: application/json;charset=UTF-8
  body:
    name: "Kiwi"
    subName: ""
    quantity: 75
  matchers:
    headers:
      - key: Content-Type
        regex: "application/json.*"
    body:
      - path: $.quantity
        type: by_regex
        value: "[0-9]+"
      - path: $.name
        type: by_regex
        predefined: only_alpha_unicode
  metadata:
    restdocs:
      headers:
        - key: Content-Type
          description: "Produce endpoint expects JSON encoded request bodies"
      body:
        - path: $.name
          description: "Name of new produce item"
        - path: $.subName
          description: "Sub-name of new produce item providing a more specific name for the produce item"
        - path: $.quantity
          description: "Number of produce item currently in stock"
response:
  status: 200
  body:
    id: 10
    name: "Kiwi"
    subName: ""
    quantity: 75
  headers:
    Content-Type: application/json;charset=UTF-8
  matchers:
    body:
      - path: $.id
        type: by_regex
        value: "[0-9]+"
  metadata:
    restdocs:
      headers:
        - key: Content-Type
          description: "Produce endpoint provides responses in JSON"
      body:
        - path: $.id
          description: "Unique id of new produce item"
        - path: $.name
          description: "Name of new produce item"
        - path: $.subName
          description: "Sub-name of new produce item providing a more specific name for the produce item"
        - path: $.quantity
          description: "Number of produce item currently in stock"
```

For Groovy it would be either a similar map or just calling rest docs methods

```groovy
metadata("restdocs": RestDocsStaticMethods.foo().bar().baz())
```

**Comment by artemptushkin** [comment]
Ah, I get it, it was YAML contract. I'm used to groovy :)

Yes, it is nice so far!

**Pull request merged**
