### PR TITLE
Added default error handler for XmlSlurper to avoid printing annoying

### PR DESCRIPTION
**Pull request by konstantinshevchuk**
Fix for annoying error [Fatal Error] :1:1: Content is not allowed in prolog.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@konstantinshevchuk Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-contract&pullRequestId=868)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-cloud/spring-cloud-contract&pullRequestId=868) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@konstantinshevchuk Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-contract&pullRequestId=868)!

**Comment by konstantinshevchuk** [comment]
small pseudo code
Existing: 
`    try {
        new XmlSlurper().parseText("Not valid XML")
    } catch (Exception e){
        //ignore it
    }`

Console output:

`[Fatal Error] :1:1: Content is not allowed in prolog.`

New one 

`try {
        def slurper = new XmlSlurper()
        slurper.setErrorHandler(new DefaultHandler())
        slurper.parseText("Not valid XML")
    } catch (Exception e){
        //ignore it
    }`

Console output:

**Comment by ryanjbaxter** [comment]
Can you submit this PR against the 2.0.x branch?

**Comment by konstantinshevchuk** [comment]
I will create new PR against the 2.0.x branch.

**Comment by konstantinshevchuk** [comment]
New PR https://github.com/spring-cloud/spring-cloud-contract/pull/871 is constantly failing. Please read comments.

**Pull request closed without merging**
