### PR TITLE
Use Gradle JVM Test Suite Plugin

### PR DESCRIPTION
**Pull request by shanman190**
Fixes 1863.

This has a small complexity in so far as for Gradle 7.6 there was a breaking change for plugin authors. As such, since Spring Boot has a strict requirement of Gradle 7.4+, I went ahead and used reflection to enable Gradle 7.4-7.5.1 compatibility.

### CODE REVIEW

**Comment by shanman190** [comment]
@marcingrzejszczak, here's the JVM Test Suite plugin usage that you contacted me about. Sorry that it took a little longer to turn around to you all. :smile:

**Comment by shanman190** [comment]
Not quite sure what's up with the failed build. All of them succeed via Gradle directly for me locally. Any ideas @marcingrzejszczak ?

**Comment by marcingrzejszczak** [comment]
```
[INFO] FAILURE: Build failed with an exception.
[INFO] 
[INFO] * Where:
[INFO] Build file '/home/runner/work/spring-cloud-contract/spring-cloud-contract/samples/standalone/dsl/http-server/build.gradle' line: 5
[INFO] 
[INFO] * What went wrong:
[INFO] An exception occurred applying plugin request [id: 'org.springframework.cloud.contract', artifact: 'org.springframework.cloud:spring-cloud-contract-gradle-plugin:4.0.3-SNAPSHOT']
[INFO] > Failed to apply plugin 'org.springframework.cloud.contract'.
[INFO]    > Could not create domain object 'contractTest' (JvmTestSuite)
[INFO] 
[INFO] * Try:
```

It failed because of this which is strictly related to what you've been doing :thinking:

**Comment by shanman190** [comment]
@marcingrzejszczak, managed to figure out what was going on and fix it. PR's good now.

**Pull request merged**
