### PR TITLE
Added support of query parameters for RestDocs for WireMock stubs

### PR DESCRIPTION
**Pull request by leebake**
In WireMockSnippet requestPattern is generated by urlEqualTo method. In order to working properly with queryParameters it should be urlPathEqualTo method. Please see the example below:

Generated currently by WireMockSnippet
```
{
  "id" : "3a08a940-3efa-4086-aaf2-fd3718e23bd5",
  "request" : {
    "url" : "/test",
    "method" : "GET",
    "queryParameters" : {
      "userId" : {
        "equalTo" : "11"
      }
    }
  },
  "response" : {
    "status" : 200,
    "body" : "{}" 
  },
  "uuid" : "3a08a940-3efa-4086-aaf2-fd3718e23bd5"
}
```
Request was not matched:
```
 curl  'http://localhost:8080/test?userId=11'

                                               Request was not matched
                                               =======================

-----------------------------------------------------------------------------------------------------------------------
| Closest stub                                             | Request                                                  |
-----------------------------------------------------------------------------------------------------------------------
                                                           |
GET                                                        | GET
/test                                                      | /test?userId=11                                     <<<<< URL does not match
                                                           |
Query: userId = 11                                         | userId: 11
                                                           |
                                                           |
-----------------------------------------------------------------------------------------------------------------------
```
Should generate:
```
{
  "id" : "3a08a940-3efa-4086-aaf2-fd3718e23bd5",
  "request" : {
    "urlPath" : "/test",
    "method" : "GET",
    "queryParameters" : {
      "userId" : {
        "equalTo" : "11"
      }
    }
  },
  "response" : {
    "status" : 200,
    "body" : "{}" 
  },
  "uuid" : "3a08a940-3efa-4086-aaf2-fd3718e23bd5"
}
```
Request matched:
```
curl  'http://localhost:8080/test?userId=11'
{}
```

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@leebake Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-contract&pullRequestId=1237)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-cloud/spring-cloud-contract&pullRequestId=1237) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@leebake Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-contract&pullRequestId=1237)!

**Comment by marcingrzejszczak** [comment]
Cześć @leebake ! :) Would you mind adding a small test for this case?

**Comment by leebake** [comment]
@marcingrzejszczak as you wish ;)

**Comment by marcingrzejszczak** [comment]
Thanks @leebake for your contribution!

**Comment by leebake** [comment]
@marcingrzejszczak is there any chance to merge and release it in 2.1.x or should I create new PR?

**Comment by marcingrzejszczak** [comment]
Cherry-picked to 2.1.x :)

**Comment by leebake** [comment]
Thank you so much!

**Pull request merged**
