### PR TITLE
Update README.adoc Mentioning both Maven and Gradle plugin testFramework and targetFramework property

### PR DESCRIPTION
**Pull request by jntakpe**
Fix wrong property name to change the test framework.

### CODE REVIEW

**Comment by marcingrzejszczak** [comment]
The documentation is generated from the docs module. Can you update the files there?

**Comment by jntakpe** [comment]
Yes of course

**Comment by jntakpe** [comment]
@marcingrzejszczak Updated actually testFramework is used by Maven plugin and targetFramework by Gradle

**Comment by OlgaMaciaszek** [comment]
Yes, @jntakpe the two different names were a bug - it's been fixed here: https://github.com/spring-cloud/spring-cloud-contract/commit/8c773868160ed6000701c154f95b02c79b6a10e5 
so now both will have the right name.

**Pull request closed without merging**
