### PR TITLE
Fix StackOverflow exception when stubTrigger runs contract with body based on json file

### PR DESCRIPTION
**Pull request by abialas**

### CODE REVIEW

**Comment by marcingrzejszczak** [comment]
Can you please create a test too? And maybe point to the stckoverflow isaue? Thanks!

**Comment by abialas** [comment]
I added the test which verifies there is no more StackOverflow error when trying to extract body value from the json file. There was no issue - I just discovered it when trying to run stubs generated with a body from the json file.

**Comment by marcingrzejszczak** [comment]
So can we close this?

**Comment by abialas** [comment]
If this fix looks ok for you then yes - it can be merged and closed.

**Comment by marcingrzejszczak** [comment]
One of the tests is failing on circle ci, can you please check it out?

**Pull request merged**
