### PR TITLE
Implement JSON matching with JSON Content-Type

### LINKED ISSUE #116: RestDocs should use JSON matching with JSON Content-type
spring-cloud-contract-wiremock RestDocs stub generator uses WireMock equalTo matcher for JSON instead of equalToJson. Which makes the stubs near unusable as different applications can generate completely different JSON for the same data.

It would be nice if WireMockSnippet would check the Content-type and generate the request matcher accordingly.

### PR DESCRIPTION
**Pull request by patrice-conil**
fixes #116

### CODE REVIEW

**Comment by marcingrzejszczak** [comment]
For some reason circle ci hasn't built this PR. Interesting...

**Comment by patrice-conil** [comment]
Hi Marcin,
I'm unable to build the global project ... gradle plugin build failed
I've the same failure with original 1.0.x as you can see below.
Any idea on what happened ?

============================
         /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
        ( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
         \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
          '  |____| .__|_| |_|_| |_\__, | / / / /
         =========|_|==============|___/=/_/_/_/
         :: Spring Boot ::        (v1.4.0.RELEASE)

        2017-02-01 09:29:52.486  INFO 5655 --- [    Test worker] o.s.cloud.LoanApplicationServiceSpec     : Starting LoanApplicationServiceSpec on macbook-pro-de-patrice-2.home with PID 5655 (/Users/pyec6553/IdeaProjects/spring-cloud-contract/spring-cloud-contract-tools/spring-cloud-contract-gradle-plugin/build/generated-tests/SampleJerseyProjectSpec/2017-02-01_09-29-40/loanApplicationService/build/classes/test started by pyec6553 in /Users/pyec6553/IdeaProjects/spring-cloud-contract/spring-cloud-contract-tools/spring-cloud-contract-gradle-plugin/build/generated-tests/SampleJerseyProjectSpec/2017-02-01_09-29-40/loanApplicationService)
        2017-02-01 09:29:52.487  INFO 5655 --- [    Test worker] o.s.cloud.LoanApplicationServiceSpec     : No active profile set, falling back to default profiles: default
        2017-02-01 09:29:52.516  INFO 5655 --- [    Test worker] s.c.a.AnnotationConfigApplicationContext : Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@12b7904d: startup date [Wed Feb 01 09:29:52 CET 2017]; root of context hierarchy
        2017-02-01 09:29:52.883  INFO 5655 --- [    Test worker] f.a.AutowiredAnnotationBeanPostProcessor : JSR-330 'javax.inject.Inject' annotation found and supported for autowiring
        2017-02-01 09:29:53.134  INFO 5655 --- [    Test worker] o.s.cloud.LoanApplicationServiceSpec     : Started LoanApplicationServiceSpec in 0.921 seconds (JVM running for 1.824)
        2017-02-01 09:29:53.243  INFO 5655 --- [qtp771319961-20] /                                        : RequestHandlerClass from context returned com.github.tomakehurst.wiremock.http.StubRequestHandler. Normalized mapped under returned 'null'
        2017-02-01 09:29:53.329 ERROR 5655 --- [qtp771319961-20] WireMock                                 : Request was not matched:
        {
          "url" : "/fraudcheck",
          "absoluteUrl" : "http://localhost:19792/fraudcheck",
          "method" : "PUT",
          "clientIp" : "127.0.0.1",
          "headers" : {
            "User-Agent" : "Java/1.8.0_92",
            "Connection" : "keep-alive",
            "Host" : "localhost:19792",
            "Accept" : "application/json, application/*+json",
            "Content-Length" : "49",
            "Content-Type" : "application/vnd.fraud.v1+json"
          },
          "cookies" : { },
          "browserProxyRequest" : false,
          "loggedDate" : 1485937793271,
          "bodyAsBase64" : "eyJjbGllbnRQZXNlbCI6IjEyMzQ1Njc4OTAiLCJsb2FuQW1vdW50IjoxMjMuMTIzfQ==",
          "body" : "{\"clientPesel\":\"1234567890\",\"loanAmount\":123.123}",
          "loggedDateString" : "2017-02-01T08:29:53Z"
        }
    Gradle Test Executor 2 finished executing tests.
    2017-02-01 09:29:53.368  INFO 5655 --- [      Thread-13] s.c.a.AnnotationConfigApplicationContext : Closing org.springframework.context.annotation.AnnotationConfigApplicationContext@12b7904d: startup date [Wed Feb 01 09:29:52 CET 2017]; root of context hierarchy

    org.springframework.cloud.LoanApplicationServiceSpec > should successfully apply for loan FAILED
        org.springframework.web.client.HttpClientErrorException: 404 Not Found
            at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:91)
            at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:667)
            at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:620)
            at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:580)
            at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:498)
            at org.springframework.cloud.frauddetection.LoanApplicationService.sendRequestToFraudDetectionService(LoanApplicationService.java:62)
            at org.springframework.cloud.frauddetection.LoanApplicationService.loanApplication(LoanApplicationService.java:51)
            at org.springframework.cloud.LoanApplicationServiceSpec.should successfully apply for loan(LoanApplicationServiceSpec.groovy:54)

    org.springframework.cloud.LoanApplicationServiceSpec > should be rejected due to abnormal loan amount STANDARD_OUT
        2017-02-01 09:29:53.345 ERROR 5655 --- [qtp771319961-21] WireMock                                 : Request was not matched:
        {
          "url" : "/fraudcheck",
          "absoluteUrl" : "http://localhost:19792/fraudcheck",
          "method" : "PUT",
          "clientIp" : "127.0.0.1",
          "headers" : {
            "User-Agent" : "Java/1.8.0_92",
            "Connection" : "keep-alive",
            "Host" : "localhost:19792",
            "Accept" : "application/json, application/*+json",
            "Content-Length" : "47",
            "Content-Type" : "application/vnd.fraud.v1+json"
          },
          "cookies" : { },
          "browserProxyRequest" : false,
          "loggedDate" : 1485937793342,
          "bodyAsBase64" : "eyJjbGllbnRQZXNlbCI6IjEyMzQ1Njc4OTAiLCJsb2FuQW1vdW50Ijo5OTk5OX0=",
          "body" : "{\"clientPesel\":\"1234567890\",\"loanAmount\":99999}",
          "loggedDateString" : "2017-02-01T08:29:53Z"
        }

    org.springframework.cloud.LoanApplicationServiceSpec > should be rejected due to abnormal loan amount FAILED
        org.springframework.web.client.HttpClientErrorException: 404 Not Found
            at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:91)
            at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:667)
            at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:620)
            at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:580)
            at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:498)
            at org.springframework.cloud.frauddetection.LoanApplicationService.sendRequestToFraudDetectionService(LoanApplicationService.java:62)
            at org.springframework.cloud.frauddetection.LoanApplicationService.loanApplication(LoanApplicationService.java:51)
            at org.springframework.cloud.LoanApplicationServiceSpec.should be rejected due to abnormal loan amount(LoanApplicationServiceSpec.groovy:65)

    org.springframework.cloud.LoanApplicationServiceSpec STANDARD_OUT
        2017-02-01 09:29:53.351  INFO 5655 --- [    Test worker] o.eclipse.jetty.server.ServerConnector   : Stopped ServerConnector@3ff3c372{HTTP/1.1}{0.0.0.0:19792}
        2017-02-01 09:29:53.352  INFO 5655 --- [    Test worker] o.e.jetty.server.handler.ContextHandler  : Stopped o.e.j.s.ServletContextHandler@16cbf5a2{/,null,UNAVAILABLE}
        2017-02-01 09:29:53.353  INFO 5655 --- [    Test worker] o.e.jetty.server.handler.ContextHandler  : Stopped o.e.j.s.ServletContextHandler@40e458a0{/__admin,null,UNAVAILABLE}

    2 tests completed, 2 failed
    Finished generating test XML results (0.011 secs) into: /Users/pyec6553/IdeaProjects/spring-cloud-contract/spring-cloud-contract-tools/spring-cloud-contract-gradle-plugin/build/generated-tests/SampleJerseyProjectSpec/2017-02-01_09-29-40/loanApplicationService/build/test-results/test
    Generating HTML test report...
    Finished generating test html results (0.009 secs) into: /Users/pyec6553/IdeaProjects/spring-cloud-contract/spring-cloud-contract-tools/spring-cloud-contract-gradle-plugin/build/generated-tests/SampleJerseyProjectSpec/2017-02-01_09-29-40/loanApplicationService/build/reports/tests/test
    :loanApplicationService:test FAILED
    :loanApplicationService:test (Thread[Connection worker,5,main]) completed. Took 2.206 secs.

    FAILURE: Build failed with an exception.

**Comment by marcingrzejszczak** [comment]
Interesting... are you using Windows or Linux? I'm waiting for CircleCI to finish cause maybe it will work there without any issues

**Comment by patrice-conil** [comment]
I'm using macosX El Capitan

**Comment by marcingrzejszczak** [comment]
Congrats @patrice-conil on the PR :D

I have no idea why it didn't pass for you - you can check in the test results of Gradle additional information about the reason for this.  It passed on Circle CI.

**Comment by patrice-conil** [comment]
Thanks Marcin,
Any idea of the release date ?

**Comment by marcingrzejszczak** [comment]
We've just released M1 of Dalston, so the earliest will be M2 of Dalston. `1.0.4` - don't really know when :/ If you really, really, really need it you can use Jitpack for the given commit - https://jitpack.io/#spring-cloud/spring-cloud-contract/1337bb0dea

**Comment by patrice-conil** [comment]
I keep it in mind, we release our project around Feb 8th.
What's the meaning of the bug label added ?

**Comment by marcingrzejszczak** [comment]
It means that I thought that this PR is fixing a bug - but obviously it's an enhancement...

**Comment by patrice-conil** [comment]
Ok it was just to familiarize myself with the semantic :) .

**Pull request merged**
