### PR TITLE
gh-245: Implementation of new DslProperty Creation methods

### PR DESCRIPTION
**Pull request by pfrank13**
Added anyIso8601DateTimeWithTimeZone, anyNotEmptyOrWhitespaceString, enumOf(String... values) contract dsl convenience methods in order to create and validate data that are common in many APIs.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@pfrank13 Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-contract&pullRequestId=246)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-cloud/spring-cloud-contract&pullRequestId=246) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@pfrank13 Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-contract&pullRequestId=246)!

**Comment by marcingrzejszczak** [comment]
Sth's wrong with the branches. It will be best if you close this PR, create a fresh new branch from `1.0.x` branch, apply a patch with your feature and create a PR from that branch.

**Comment by pfrank13** [comment]
That's the plan, I had already rebased in changes from master into my gh-245 branch, I'm currently working on patching a new branch gh-245_1.0.x and I'll close this PR and open a new one.

**Comment by pfrank13** [comment]
Closing this pull request as the branch gh-245 was based off of master and need to be on 1.0.x

**Pull request closed without merging**
