### PR TITLE
Fix bad commiter info from #491

### PR DESCRIPTION
**Pull request by regevbr**

### CODE REVIEW

**Comment by regevbr** [comment]
@marcingrzejszczak I push the commits of issue #491 with no proper git config and as such it created bad commiter info (non existing user), this PR fixes that if you can please check it out

**Comment by marcingrzejszczak** [comment]
Sure, can you set this PR vs the `1.1.x` branch?

**Comment by regevbr** [comment]
This commit was ported only to 1.2.x, do you want me to create another PR to it?

**Comment by marcingrzejszczak** [comment]
Was it? Ok, so create a PR to 1.2.x

**Comment by regevbr** [comment]
Sure

**Comment by regevbr** [comment]
see #498

**Comment by marcingrzejszczak** [comment]
Done via https://github.com/spring-cloud/spring-cloud-contract/commit/f69a2f63d004eab950bb9fda737e6e89c3478ea6

**Pull request closed without merging**
