### PR TITLE
Documentation - Update title style in section 2.2.

### LINKED ISSUE #1349: Documentation - The 2.2 section "On the Consumer Side" has not the correct title style.
The 2.2 section of the [documentation](https://spring.io/projects/spring-cloud-contract) page "On the Consumer Side" has not the correct style like section 2.1 has - "On the Producer Side".
I have attached an image as evidence of the issue.
scc documentation - two different styles

### PR DESCRIPTION
**Pull request by darek1024**
Fixes #1349

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@darek1024 Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-contract&pullRequestId=1364)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-cloud/spring-cloud-contract&pullRequestId=1364) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@darek1024 Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-contract&pullRequestId=1364)!

**Comment by marcingrzejszczak** [comment]
Congrats @darek1024 on your first contribution to the project :sparkles: :rocket: :fire:

**Comment by darek1024** [comment]
So proud @marcingrzejszczak 🥰🥳

**Pull request merged**
