### PR TITLE
#1633 - Random https port in annotation AutoConfigureWireMock is broken issue

### PR DESCRIPTION
**Pull request by GodwinMaravai**
Random https port in annotation AutoConfigureWireMock is broken issue - fix

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@GodwinMaravai Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-contract&pullRequestId=1653)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-cloud/spring-cloud-contract&pullRequestId=1653) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@GodwinMaravai Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-contract&pullRequestId=1653)!

**Comment by marcingrzejszczak** [comment]
Congrats @GodwinMaravai on your first contribution :)

**Comment by yanivnahoum** [comment]
This seems to have broken the prior behavior in which `AutoConfigureWireMock` is used with the default settings: it now configures a random httpsPort and calling WiremockServer::baseUrl() now returns an https url.

**Comment by marcingrzejszczak** [comment]
Can you create an issue with a test that currently breaks?

**Comment by yanivnahoum** [comment]
I spent a while debugging the failed tests, even though I had a few workarounds that made it work.
What's happening is that the failing test class is annotated with `@RestClientTest` along with `@AutoConfigureMockRestServiceServer(enabled = false)` to suppress the creation of spring's `MockRestServiceServer`.
This triggers the application lifecycle event handled by `org.springframework.cloud.contract.wiremock.WireMockApplicationListener` **before**  `@AutoConfigureWireMock` is initialized and it registers dynamic http & https ports.
If you then try to configure your client's RestTemplate with the WireMockServer's baseUrl, you'll get an https://localhost:xxxxx url:
```java
    @TestConfiguration(proxyBeanMethods = false)
    static class AdditionalConfig {

        @Bean
        // Allow WireMockServer to be created and started
        @Lazy
        RestTemplateCustomizer customizer(WireMockServer server) {
            return restTemplate -> RootUriTemplateHandler.addTo(restTemplate, server.baseUrl());
        }
    }
```

This actually fails the test only if you **don't** use Apache's HttpClient as the `RestTemplate`'s internal http client since when using Apache, the `RestTemplate` is customized with a `TrustSelfSignedStrategy` and a `NoopHostnameVerifier`.
And indeed I'm using OkHttp's client.

**Pull request merged**
