### PR TITLE
Add stub CORS enabled option to WireMock start

### PR DESCRIPTION
**Pull request by szatyinadam**
Configure WireMock's CORS configuration via environmental variable.

#1655

### CODE REVIEW

**Comment by szatyinadam** [comment]
@marcingrzejszczak What is the preferred way, class to implement config options? What config options required from the [WireMockConfiguration](https://github.com/tomakehurst/wiremock/blob/master/src/main/java/com/github/tomakehurst/wiremock/core/WireMockConfiguration.java) ? I assume some of them is not needed, for example `threadPoolFactoy`.

**Comment by marcingrzejszczak** [comment]
We already have the `wiremock` properties -> https://github.com/spring-cloud/spring-cloud-contract/blob/c42293b14f6636a459205e7594e328f0aba6ee79/spring-cloud-contract-wiremock/src/main/java/org/springframework/cloud/contract/wiremock/WireMockConfiguration.java#L327-L452 . We could make this bean public and reuse it and ensure that all options available here http://wiremock.org/docs/running-standalone/ can be set

**Comment by marcingrzejszczak** [comment]
@szatyinadam how is it going with the PR? :)

**Comment by marcingrzejszczak** [comment]
I'm closing the PR due to inactivity

**Comment by aosorio1** [comment]
@marcingrzejszczak  I was waiting eagerly that this PR got merged just to see that it was closed. Right now, it's not possible to disable WireMock request journal via properties and this makes it difficult to use WireMock in scenarios where journal should be disabled such as load testing. Any chances of reopening this issue?

**Pull request closed without merging**
