### PR TITLE
Add capability to set initial request context. Fixes gh-1740.

### PR DESCRIPTION
**Pull request by mathieu-amblard**
Add context field for the request to be able to generate providerStates when a Contract for HTTP to a PACT.

### CODE REVIEW

**Comment by marcingrzejszczak** [comment]
I saw that you've modified `Contract` to add `requestContext`. Maybe we can leverage the metadata section? That way for PACT we can add arbitrary things without impacting how Contract looks like. WDYT?

**Comment by marcingrzejszczak** [comment]
The problem is that for the standard HTTP contract that uses MockMvc that field is irrelevant. I think we should go with the metadata approach.

**Comment by mathieu-amblard** [comment]
Yes, you are right, so let's go for the metadata approach.

**Comment by mathieu-amblard** [comment]
Hi @marcingrzejszczak,
I just push a new version with the metadata approach.
Thanks in advance for your feedbacks.

**Pull request merged**
