### PR TITLE
Windows stubs path fix

### PR DESCRIPTION
**Pull request by Budlee**
Fixes gh-1374.

This will fix that bugs when running on Windows.
Tested the fix on Windows and on Mac

### CODE REVIEW

**Comment by Budlee** [comment]
Found this failed  in Master  and in 2.2.2

**Comment by Budlee** [comment]
Looks like the build is failing at the moment anyway and I  made  this change on top of  master. Can you let me know what you want me  to do

THanks

**Comment by Budlee** [comment]
@OlgaMaciaszek, Sure I can re submit this.
What additional tests are you looking for? The additional windows filepath integration test covers the changes and the previous tests cover a unix/mac file path structure
Thanks

**Comment by OlgaMaciaszek** [comment]
yes, @Budlee I see you've added another commit with the test. Thanks. That will do. Please resubmit these changes against the `2.2.x` branch.

**Comment by Budlee** [comment]
Can you close this PR. I have created a new one as was in a bit of git hell
Windows file path fix#1374 (https://github.com/spring-cloud/spring-cloud-contract/pull/1402)

**Comment by OlgaMaciaszek** [comment]
Closing in favour of https://github.com/spring-cloud/spring-cloud-contract/pull/1402.

**Pull request closed without merging**
