### PR TITLE
Support loading limited context for stub runner tests

### PR DESCRIPTION
**Pull request by bijukunjummen**
#473 - @marcingrzejszczak , this is still Work in progress, but I wanted to send you a PR to see if this directionally looks okay. Can you please review when you get a chance.

### CODE REVIEW

**Comment by marcingrzejszczak** [comment]
This looks very good! I'd only add `@since 2.0.0` in the javadocs and add some documentation. Anything you would add @dsyer ?

**Comment by dsyer** [comment]
We prefer test classes to be called `*Tests`. That should be easy to change.

**Comment by dsyer** [comment]
I don't really understand the problem this solves, so some documentation will be helpful as well. Otherwise there will be a lot of confusion about why this is needed in addition to `@AutoConfigureStubRunner` (is it, actually, needed?).

**Comment by marcingrzejszczak** [comment]
My understanding is that you don't need the full Spring Boot context to use StubRunner thanks to this, am I correct @bijukunjummen ?

**Comment by dsyer** [comment]
Is there a way to just use `@AutoconfigureStubRunner` in a normal (existing) test slice?

**Comment by bijukunjummen** [comment]
@marcingrzejszczak , @dsyer , I have now removed the slice test for stub runner and instead modified like you suggested `@AutoConfigureStubRunner` to load only the relevant auto-configurations, this way it works in combination with any other test slice.

**Comment by marcingrzejszczak** [comment]
Thanks a lot @bijukunjummen !

**Pull request merged**
