### PR TITLE
[#500] Messaging contracts per topic

### PR DESCRIPTION
**Pull request by anikitchuk**
Updated doc for messaging contracts

### CODE REVIEW

**Comment by marcingrzejszczak** [comment]
That looks great! I wonder if it wouldn't be worth it to also add a Gradle setup. WDYT? I can't try it out but I guess we would need to provide (all of this is pseudo code that I don't even know that would work)

A custom configuration for the `common-repo` dependency (e.g. `contracts`)

```
ext {
  contractsArtifactId = "common-repo"
  contractsVersion = "1.2.3"
}


configurations {
    contracts {
       transitive = false
    }
}
```

providing the dependency

```
dependencies {
    contracts "com.exampe:${contractsArtifactId}:${contractsVersion}"
}

task to download deps

```
task getContracts(type: Copy) {
    from configurations.contracts
    into new File(project.buildDir, "downloadedContracts")
}
```

and an unzip task

```
task unzipContracts(type: Copy) {
    def zipFile = new File(project.buildDir, "downloadedContracts/${contractsArtifactId}-${contractsVersion}.jar")
    def outputDir = file("${buildDir}/unpackedContracts")
 
    from zipTree(zipFile)
    into outputDir
}
```

the deletion task

```
task deleteUnwantedContracts(type: Delete) {
    delete fileTree("${buildDir}/unpackedContracts").matching {
          exclude "**/firstTopic/**", "**/secondTopic/**" // not sure if that accepts an ant pattern
    }
}
```

task dependencies (again, I'm not sure of this :P )

```
unzipContracts.dependsOn("getContracts")
deleteUnwantedContracts.dependsOn("unzipContracts")
build.dependsOn("deleteUnwantedContracts")
```

and of course the `contracts {}` closure would now point to the proper directory

also do you think you could set up a sample for this? We could then put it to https://github.com/spring-cloud-samples/spring-cloud-contract-samples

**Comment by marcingrzejszczak** [comment]
Ping @anikitchuk ?

**Comment by anikitchuk** [comment]
Hi, @marcingrzejszczak! I'll setup the Gradle project, check it out and then will update this PR.

**Comment by marcingrzejszczak** [comment]
Awesome! Thanks a lot!

**Comment by anikitchuk** [comment]
Hi, @marcingrzejszczak! I've updated the PR with working Gradle configuration and a bit later will setup sample project.

**Pull request merged**
