### PR TITLE
Fix #471

### LINKED ISSUE #471: Number pattern allows empty value
Creating a test of

`
test(
    [
        [
             "price" : regex(number())
        ]
    ]
)
`

accepts empty values. This leads to generated tests that do not assert the correctness of field names.

Suppose we test this against a JSON like this one:

`
[
  {
	"priceFoo": 123
 }
]
`

A test will be generated:

`assertThatJson(parsedJson).array().contains("['price']").matches("-?\\d*(\\.\\d+)?");`

This test will not fail for any wrong field names for "price" as the regex accepts empty values.
Is this intended? If so, how can I write a test that fails for wrong field names?

### PR DESCRIPTION
**Pull request by JohannesDorn**
Don't allow empty values for numbers

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@JohannesDorn Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-contract&pullRequestId=472)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-cloud/spring-cloud-contract&pullRequestId=472) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@JohannesDorn Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-contract&pullRequestId=472)!

**Comment by marcingrzejszczak** [comment]
I've applied your fix to 1.2.x branch (https://github.com/spring-cloud/spring-cloud-contract/commit/ea064d9c82694e8509fd36390c2d76a27cf53f13). Congrats on becoming Spring Cloud Contract contributor :D

**Comment by JohannesDorn** [comment]
Thanks!

Can you give me a rough ETA on when this will be released?

**Comment by marcingrzejszczak** [comment]
we've just released sc-contract, so it will take some time... You can workaround this by providing the regex manually `regex("your regex")`

**Pull request merged**
